### ISSUE TITLE
Misaligned Holes on the Main Plate

### ISSUE THREAD

**Issue by glydrfreak** [openppg/Mechanical#2]
Below are the images I copied from the forum. I tried assembling the parts in OnShape and confirmed the misalignments. I would like the updated part(s) as soon as they are available. Surely someone must have the updated part files, especially if they are in production.
![image](https://user-images.githubusercontent.com/29639561/40335797-e3751d84-5d22-11e8-8ea7-dde6c4dec194.png)
![image](https://user-images.githubusercontent.com/29639561/40335809-f1ed43d2-5d22-11e8-84de-29d31a862fc6.png)

**Comment by davek79** [comment]
The new "main_plate" replaces front_plate and rear_plate and resolves this issue.
