### ISSUE TITLE
Arm and Main Plate Interference

### ISSUE THREAD

**Issue by glydrfreak** [openppg/Mechanical#3]
See image below:
![image](https://user-images.githubusercontent.com/29639561/40336229-a2562930-5d25-11e8-9c6d-3f4bff4e5f6b.png)

**Comment by davek79** [comment]
![image](https://user-images.githubusercontent.com/36675149/40462194-deb66972-5edc-11e8-8c99-25ac92b10004.png)

Resolved with new arm.step files

**Comment by glydrfreak** [comment]
Awesome!
